### ISSUE TITLE
Issue with POSTing json data

### ISSUE THREAD

**Issue by christohill** [pstaender/silverstripe-restful-api#1]
I seem to be having an issue POSTing json from both AngularJS and jQuery. Testing worked fine with the Chrome extensions Postman and Advanced REST Client, but when using JavaScript it returns an error.

Example: auth/session
Returns: 

```
{"code":422,"error":"The JSON property `email` is required"}
```

POST Source (correct credentials): 

```
{"email":"admin","password":"password"}
```

The only difference between the Postman and Angular/jQuery POST's is the Content-Type:
Postman: "application/json"
ng/jQuery: "application/json; charset=UTF-8"

Any ideas?

**Comment by pstaender** [comment]
Hi,

I think the problem is jQuery (I'm not working with AngularJS, so maybe it's the same issue), see here: https://stackoverflow.com/questions/6587221/send-json-data-with-jquery

Using `JSON.stringify` and saying explicitly `contentType: 'application/json` solved the problem with jQuery:

``` coffeescript
$.ajax
  type: 'POST'
  url: 'auth/session'
  data: JSON.stringify({ email: 'email', password: 'password' })
  contentType: 'application/json'
  success: (res) ->
    console.log res
```

returns s.th. like

``` json
{
  "session": {
    "member": { … },
  "code": 201,
  "message": "resource created succesfully"
}
```

**Comment by christohill** [comment]
This is almost the exact method I was trying and getting the issue. Here's my jQuery:

``` jQuery
    $.ajax({

        method: "POST",
        url: "http://localhost/notes/web/auth/session",
        data: JSON.stringify({
            email: 'admin',
            password: 'password'
        }),
        contentType: 'application/json'

    });
```

POST Source:

``` json
{"email":"admin","password":"password"}
```

Request header Content-Type (from Firebug)

```
Content-Type: application/json; charset=UTF-8
```

**Comment by christohill** [comment]
Just to add on to this. I get the same issue with required fields on both POST and PUT when extending the API controller.

I've worked around this by adding this to the init() block.

``` php
if($this->request->isPOST() || $this->request->isPUT()) {
    $this->request->addHeader('Content-Type', 'application/json');
}
```

But this limits me to only be able to POST json which is a bit of a bummer.

**Comment by pstaender** [comment]
Yes, you're right. I found the bug: https://github.com/pstaender/silverstripe-restful-api/blob/master/code/controller/ApiController.php#L111
It strictly checks for `json` at the end of s string, I'll fix that that weekend and publish a new release. As hotfix you could replace that line with

``` php
    if (preg_match('/application\/json/i',$contentType)) {
```

this will be the fix I'll provide.

**Comment by christohill** [comment]
Nice catch Phillip, that worked. I've implemented the fix for now and will look out for when you push the new updated.

Thanks!
